<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Application\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'location', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'aboutme', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'homepage', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'avatar', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'teacher', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'student', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'permission', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'tokens', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'skills', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'notifications', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'user_groups', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'timetable', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstlogin', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'mute', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'documents');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'location', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'aboutme', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'homepage', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'avatar', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'teacher', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'student', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'permission', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'tokens', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'skills', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'notifications', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'user_groups', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'timetable', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstlogin', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'mute', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'documents');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacher', array());

        return parent::getTeacher();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeacher($teacher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeacher', array($teacher));

        return parent::setTeacher($teacher);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', array());

        return parent::getStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudent($student)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', array($student));

        return parent::setStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermission', array());

        return parent::getPermission();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermission($permission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermission', array($permission));

        return parent::setPermission($permission);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function getTokens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTokens', array());

        return parent::getTokens();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotifications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotifications', array());

        return parent::getNotifications();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser_groups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser_groups', array());

        return parent::getUser_groups();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', array($avatar));

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function setTokens($tokens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTokens', array($tokens));

        return parent::setTokens($tokens);
    }

    /**
     * {@inheritDoc}
     */
    public function setNotifications($notifications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotifications', array($notifications));

        return parent::setNotifications($notifications);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser_groups($user_groups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser_groups', array($user_groups));

        return parent::setUser_groups($user_groups);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', array());

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getAboutme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAboutme', array());

        return parent::getAboutme();
    }

    /**
     * {@inheritDoc}
     */
    public function getHomepage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomepage', array());

        return parent::getHomepage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', array($location));

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function setAboutme($aboutme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAboutme', array($aboutme));

        return parent::setAboutme($aboutme);
    }

    /**
     * {@inheritDoc}
     */
    public function setHomepage($homepage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomepage', array($homepage));

        return parent::setHomepage($homepage);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimetable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimetable', array());

        return parent::getTimetable();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimetable($timetable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimetable', array($timetable));

        return parent::setTimetable($timetable);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstlogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstlogin', array());

        return parent::getFirstlogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstlogin($firstlogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstlogin', array($firstlogin));

        return parent::setFirstlogin($firstlogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getMute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMute', array());

        return parent::getMute();
    }

    /**
     * {@inheritDoc}
     */
    public function setMute($mute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMute', array($mute));

        return parent::setMute($mute);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkills', array());

        return parent::getSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkills($skills)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkills', array($skills));

        return parent::setSkills($skills);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', array());

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocuments($documents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocuments', array($documents));

        return parent::setDocuments($documents);
    }

}
