<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("Welcome - SetUPManager")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/dataTables.bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>


        <style>
        .left {float:left;}
        .right {float:right;}
        </style>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/dataTables.bootstrap.js'))
            ->prependFile($this->basePath('js/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">SetUPManager</a>

                </div>
            </div>
        </nav>
        <div class="container">
            <?php $flash = $this->flashMessenger();
             //Error Handling
             $flash->setMessageOpenFormat('<div%s>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                 ')
                 ->setMessageSeparatorString('<br />')
                 ->setMessageCloseString('</div>');

             echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
             echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
             echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
             echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
             ?>


            <?php echo $this->content; ?>
            <br />
            <hr>
            <div id="footer">
              <div id="footer">
                <span class="left"><p>&copy; <?php echo date('Y') ?> StudyOrganizer - Free learning plattform</p></span>
                <span class="right">Build: <?php
                 echo 'r' . exec('git rev-list --count HEAD') . "." . exec('git rev-parse --short HEAD'); ?></span>
              </div>
            </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
