<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("AdminUI")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/third-party/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/third-party/bootstrap.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/third-party/bootstrap.min.js'))
            ->prependFile($this->basePath('js/third-party/dataTables.bootstrap.js'))
            ->prependFile($this->basePath('js/third-party/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('js/third-party/jquery.min.js'))
        ; ?>
    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
    