<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("StudyOrganizer")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/third-party/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/third-party/bootstrap.css')) ?>


        <style>
        .left {float:left;}
        .right {float:right;}
        </style>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/third-party/bootstrap.min.js'))
            ->prependFile($this->basePath('js/third-party/dataTables.bootstrap.js'))
            ->prependFile($this->basePath('js/third-party/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('js/third-party/jquery.min.js'))
        ; ?>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" id="logo" href="<?php echo $this->url('home') ?>">StudyOrganizer</a>

                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                      <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-fw fa-home"></i> <?php echo $this->translate('Home') ?></a></li>
                      <li><a href="<?php echo $this->url('studentui_calendar') ?>"><i class="fa fa-fw fa-calendar"></i> <?php echo $this->translate('Calendar') ?></a></li>
                      <li><a href="<?php echo $this->url('studentui_documents') ?>"><i class="fa fa-fw fa-file-text"></i> <?php echo $this->translate('Documents') ?></a></li>
                      <li><a href="<?php echo $this->url('studentui_vocabularies') ?>"><i class="fa fa-fw fa-language"></i> <?php echo $this->translate('Vocabularies') ?></a></li>
                        <li><a href="<?php echo $this->url('studentui_tools') ?>"><i class="fa fa-fw fa-flask"></i> <?php echo $this->translate('Tools') ?></a></li>
                        <li><a href="<?php echo $this->url('studentui_help') ?>"><i class="fa fa-fw fa-question-circle"></i> <?php echo $this->translate('Help') ?></a></li>
                    </ul>
					<ul class="nav navbar-nav navbar-right visible-md visible-lg">
						<li>
						<li class="dropdown" id="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<?php echo $this->translate("My Account"); ?> <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
						<li><a href="<?php echo $this->url("studentui_settings"); ?>"><i class="fa fa-fw fa-cogs"></i> <?php echo $this->translate("Settings"); ?></a></li>
                        <?php
                            if($this->lead == true) {
                                var_dump("huhu");
                            }
                        ?>
						<li><a href="<?php echo $this->url("logout"); ?>"><i class="fa fa-fw fa-sign-out"></i> <?php echo $this->translate("Logout"); ?></a></li>
						</ul>
						</li>
					</ul>
                </div>

            </div>
        </nav>
        <div class="container">
            <?php $flash = $this->flashMessenger();
             //Error Handling
             $flash->setMessageOpenFormat('<div%s>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                 ')
                 ->setMessageSeparatorString('<br />')
                 ->setMessageCloseString('</div>');

             echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
             echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
             echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
             echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
             ?>

            <?php echo $this->content; ?>
            <br />
            <hr>
            <div id="footer">
              <div id="footer">
                <span class="left"><p>&copy; <?php echo date('Y') ?> StudyOrganizer - Free learning plattform</p></span>
                <span class="right">Build: <?php
                 echo 'r' . exec('git rev-list --count HEAD') . "." . exec('git rev-parse --short HEAD'); ?></span>
              </div>
            </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
