<div class="alert alert-warning" role="alert">
<?php echo $this->
	translate("Welcome to AdminUI. Be careful with changes"); ?>
</div>
<div class="row">
	<div class="col-md-4">
		<a href="<?php echo $this->url("admin_user_list"); ?>">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-user fa-5x"></i><br/>
					<?php echo $this->
					translate("User"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
	<div class="col-md-4">
		<a href="<?php echo $this->url("admin_courses_list"); ?>">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-users fa-5x"></i><br/>
					<?php echo $this->
					translate("Courses"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
	<div class="col-md-4">
		<a href="<?php echo $this->url("admin_school_list"); ?>">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-building-o fa-5x"></i><br/>
					<?php echo $this->
					translate("Schools"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
</div>
<br/>
<div class="row">
	<div class="col-md-4">
		<a href="<?php echo $this->url('admin_permissions_list'); ?>">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-list fa-5x"></i><br/>
					<?php echo $this->
					translate("Permissions"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
	<div class="col-md-4">
		<a href="<?php echo $this->url("admin_subjects_list"); ?>">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-lightbulb-o fa-5x"></i><br/>
					<?php echo $this->
					translate("Subjects"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
	<div class="col-md-4">
		<a href="#">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-envelope fa-5x"></i><br/>
					<?php echo $this->
					translate("E-Mail"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
</div>
<br/>
<div class="row">
	<div class="col-md-4">
		<a href="#">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-file-o fa-5x"></i><br/>
					<?php echo $this->
					translate("Documents"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
	<div class="col-md-4">
		<a href="#">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-language fa-5x"></i><br/>
					<?php echo $this->
					translate("Vocabulary"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
	<div class="col-md-4">
		<a href="<?php echo $this->url("admin_settings"); ?>">
		<div class="panel panel-default">
			<div class="panel-body">
				<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
					<i class="fa fa-cog fa-5x"></i><br/>
					<?php echo $this->
					translate("Settings"); ?>
				</div>
			</div>
		</div>
		</a>
	</div>
</div>
