<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("Welcome")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/third-party/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/third-party/dataTables.bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/third-party/bootstrap.css')) ?>


        <style>
        .left {float:left;}
        .right {float:right;}
        </style>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/third-party/bootstrap.min.js'))
            ->prependFile($this->basePath('js/third-party/dataTables.bootstrap.js'))
            ->prependFile($this->basePath('js/third-party/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('js/third-party/jquery.min.js'))
        ; ?>
    </head>
    <body>
        <br />
        <p style="text-align: center;"><img src="img/assets/logo.svg" height="100px;" alt="logo" /></p>
        <br />
        
        <div class="container">
            <?php $flash = $this->flashMessenger();
             //Error Handling
             $flash->setMessageOpenFormat('<div%s>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                 ')
                 ->setMessageSeparatorString('<br />')
                 ->setMessageCloseString('</div>');

             echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
             echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
             echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
             echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
             ?>


            <?php echo $this->content; ?>
            <hr>
            <div id="footer">
              <div id="footer">
                <span class="left"><p>&copy; <?php echo date('Y') ?> StudyOrganizer - Free learning plattform</p></span>
                <span class="right">Build: <?php
                 echo 'r' . exec('git rev-list --count HEAD') . "." . exec('git rev-parse --short HEAD'); ?></span>
              </div>
            </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
